name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check formatting
        run: npm run format:check
        
      - name: Lint code
        run: npm run lint
        
      - name: Type check
        run: npm run typecheck
        
      - name: Type check (strict)
        run: npm run typecheck:strict
        continue-on-error: true # Allow this to fail initially
        
      - name: Run tests
        run: npm test
        
      - name: Build check
        run: npx expo export --platform web
        env:
          EXPO_PUBLIC_ENVIRONMENT: ci