name: Database SQL Linting

on:
  pull_request:
    paths:
      - 'migrations/**.sql'
      - 'supabase/migrations/**.sql'
      - '.sqlfluff'
      - '.github/workflows/db-lint.yml'
      - 'scripts/check-migration-filenames.sh'

jobs:
  sqlfluff-lint:
    name: SQL Linting with SQLFluff
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install SQLFluff
        run: |
          pip install sqlfluff
          sqlfluff --version
          
      - name: Lint SQL migrations
        run: |
          # Check both potential migration directories
          if [ -d "migrations" ]; then
            echo "Linting migrations/ directory..."
            sqlfluff lint migrations/
          fi
          if [ -d "supabase/migrations" ]; then
            echo "Linting supabase/migrations/ directory..."
            sqlfluff lint supabase/migrations/
          fi
      
      - name: Enforce migration filename pattern
        run: |
          echo "Checking migration filename pattern..."
          bash scripts/check-migration-filenames.sh
          
      - name: Check SQLFluff config
        run: |
          if [ -f ".sqlfluff" ]; then
            echo "SQLFluff configuration found:"
            cat .sqlfluff
          else
            echo "No .sqlfluff configuration file found"
          fi
