name: Docs Policy Enforcement

on:
  pull_request:
    branches: [ main, master ]

jobs:
  enforce-docs-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enforce docs policy (root Markdown restriction)
        run: node scripts/docs-policy-check.js
